---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.result.applabel }}
    instance: {{ .Values.result.instancelabel }}    
  name: result
spec:
  type: {{ .Values.result.service.type }}
  ports:
  - name: "result-service"
    port: 5001
    targetPort: 80
  selector:
    app: {{ .Values.result.applabel }}
    instance: {{ .Values.result.instancelabel }}    
