# Default values for webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
vote:
  replicaCount: 1
  applabel: vote
  instancelabel: vote
  image:
    name: dockersamples/examplevotingapp_vote
    tag: latest
  service:
    type: LoadBalancer

result:
  replicaCount: 1
  applabel: result
  instancelabel: result
  image:
    name: dockersamples/examplevotingapp_result
    tag: latest
  service:
    type: LoadBalancer

worker:
  replicaCount: 1
  applabel: worker
  instancelabel: worker
  image:
    name: dockersamples/examplevotingapp_worker
    tag: latest

hpa:
  redis:
    minReplicas: 1
    maxReplicas: 3
    cpu:
      averageUtilization: 60
    memory:
      averageUtilization: 60
  webapp:
    minReplicas: 1
    maxReplicas: 3
    cpu:
      averageUtilization: 60
    memory:
      averageUtilization: 60
