apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    # Based on https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf
    # user              www www;  ## Default: nobody
    
    worker_processes  auto;
    error_log         "/opt/bitnami/nginx/logs/error.log";
    pid               "/opt/bitnami/nginx/tmp/nginx.pid";
    
    events {
        worker_connections  1024;
    }
    http {
        include       mime.types;
        default_type  application/octet-stream;
        log_format    main '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status  $body_bytes_sent "$http_referer" '
                           '"$http_user_agent" "$http_x_forwarded_for"';
        access_log    "/opt/bitnami/nginx/logs/access.log";
        add_header    X-Frame-Options SAMEORIGIN;

        client_body_temp_path  "/opt/bitnami/nginx/tmp/client_body" 1 2;
        proxy_temp_path        "/opt/bitnami/nginx/tmp/proxy" 1 2;
        fastcgi_temp_path      "/opt/bitnami/nginx/tmp/fastcgi" 1 2;
        scgi_temp_path         "/opt/bitnami/nginx/tmp/scgi" 1 2;
        uwsgi_temp_path        "/opt/bitnami/nginx/tmp/uwsgi" 1 2;

        sendfile           on;
        tcp_nopush         on;
        tcp_nodelay        off;
        gzip               on;
        gzip_http_version  1.0;
        gzip_comp_level    2;
        gzip_proxied       any;
        gzip_types         text/plain text/css application/javascript text/xml application/xml+rss;
        keepalive_timeout  65;
        ssl_protocols      TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers        HIGH:!aNULL:!MD5;
        client_max_body_size 80M;
        server_tokens off;

        include  "/opt/bitnami/nginx/conf/server_blocks/*.conf";

        # HTTP Server
        server {
            # Port to listen on, can also be set in IP:PORT format
            listen  8080;
            server_name webapp.example.lan;
            return 301 https://$host$request_uri;

            include  "/opt/bitnami/nginx/conf/bitnami/*.conf";


            location /status {
                stub_status on;
                access_log   off;
                allow all;
            }

            location /vote {
                #proxy_set_header X-Forwarded-For $proxy_add_forwarded_for;
                proxy_set_header Host $host;
                proxy_pass http://vote:5000/;
                access_log "/opt/bitnami/nginx/logs/access.log";
                error_log  "/opt/bitnami/nginx/logs/error.log" warn;
              }
              location /result {
                #proxy_set_header X-Forwarded-For $proxy_add_forwarded_for;
                proxy_set_header Host $host;
                proxy_pass http://result:5001/;
                access_log "/opt/bitnami/nginx/logs/access.log";
                error_log  "/opt/bitnami/nginx/logs/error.log" warn;
              }
      }
       # HTTPS Server
       server {
           # Port to listen on, can also be set in IP:PORT format
           listen  8443 ssl http2;
           server_name webapp.example.lan;
           ssl_certificate "/opt/bitnami/nginx/conf/bitnami/certs/tls.crt";
           ssl_certificate_key "/opt/bitnami/nginx/conf/bitnami/certs/tls.key";
           ssl_trusted_certificate "/opt/bitnami/nginx/conf/bitnami/certs/ca.crt";

            location /status {
                stub_status on;
                access_log   off;
                allow all;
            }

           location /vote {
                #proxy_set_header X-Forwarded-For $proxy_add_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                proxy_pass http://vote:5000/;
                access_log "/opt/bitnami/nginx/logs/access.log";
                error_log  "/opt/bitnami/nginx/logs/error.log" warn;
           }
           location /result {
                #proxy_set_header X-Forwarded-For $proxy_add_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto https;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                #proxy_set_header $http_x_forwarded_proto $scheme;
                proxy_pass http://result:5001/;
                access_log "/opt/bitnami/nginx/logs/access.log";
                error_log  "/opt/bitnami/nginx/logs/error.log" warn;
           }
         }
    }
---


